<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SaveFooter_statuscontrol</name>
   <tag></tag>
   <elementGuidId>12c0dc13-fa9f-4ee8-8684-c1e0fb319025</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>titlefooter_statuscontrol</value>
   </webElementProperties>
</WebElementEntity>
