<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Save</name>
   <tag></tag>
   <elementGuidId>2d558eca-eda8-4b17-a5fb-1528961f73ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;footer_statuscontrol&quot;)/div[@title=&quot;Enregistrer&quot;]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer_statuscontrol&quot;)/div[@title=&quot;Enregistrer&quot;]/a</value>
   </webElementProperties>
</WebElementEntity>
